apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: weather-policy
  namespace: weather
spec:
  podSelector:
    matchLabels:
      app: weather
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector: {}  # Allows traffic from all namespaces
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
